apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  # type: NodePort
  clusterIP: 10.96.0.22
  selector:
    app: mssql
  ports:
  - port: 1433
    targetPort: 1433
    # nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2019-latest
        name: mssql
        
        #specify allocated resources
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.3"
        
        #specify env values
        env:
        - name: ACCEPT_EULA
          value: "Y" 
        - name: SA_PASSWORD
          value: "Welkom12345" 
        #specify ports
        ports:
        - containerPort: 1433
          name: mssql

        #specify volume   
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pv-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi