apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2019-latest
        name: mssql
        
        #specify allocated resources
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.3"
        
        #specify env values
        env:
        - name: ACCEPT_EULA
          value: "Y" 
        - name: SA_PASSWORD
          value: "Welkom12345" 
        #specify ports
        ports:
        - containerPort: 1433
          name: mssql

        #specify volume   
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: mssql-pv-claim